ALTER TABLE ONLY public.groups DROP CONSTRAINT groups_user_id_fkey;
ALTER TABLE ONLY public.groups_students DROP CONSTRAINT groups_students_student_id_fkey;
ALTER TABLE ONLY public.groups_students DROP CONSTRAINT groups_students_group_id_fkey;
ALTER TABLE ONLY public.groups DROP CONSTRAINT groups_course_id_fkey;
ALTER TABLE ONLY public.exercises DROP CONSTRAINT exercises_course_id_fkey;
ALTER TABLE ONLY public.email_messages DROP CONSTRAINT email_messages_student_id_fkey;
ALTER TABLE ONLY public.email_messages DROP CONSTRAINT email_messages_action_id_fkey;
ALTER TABLE ONLY public.courses_users DROP CONSTRAINT courses_users_user_id_fkey;
ALTER TABLE ONLY public.courses_users DROP CONSTRAINT courses_users_course_id_fkey;
ALTER TABLE ONLY public.course_memberships DROP CONSTRAINT course_memberships_student_id_fkey;
ALTER TABLE ONLY public.course_memberships DROP CONSTRAINT course_memberships_quit_id_fkey;
ALTER TABLE ONLY public.course_memberships DROP CONSTRAINT course_memberships_course_id_fkey;
ALTER TABLE ONLY public.chat_messages DROP CONSTRAINT chat_messages_user_id_fkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_user_id_fkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_student_id_fkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_handled_id_fkey;
ALTER TABLE ONLY public.actions_exercises DROP CONSTRAINT actions_exercises_exercise_id_fkey;
ALTER TABLE ONLY public.actions_exercises DROP CONSTRAINT actions_exercises_action_id_fkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_action_type_id_fkey;
ALTER TABLE ONLY public.action_comments DROP CONSTRAINT action_comments_user_id_fkey;
ALTER TABLE ONLY public.action_comments DROP CONSTRAINT action_comments_action_id_fkey;
ALTER TABLE ONLY public.users DROP CONSTRAINT users_pkey;
ALTER TABLE ONLY public.users DROP CONSTRAINT users_basic_user_account_key;
ALTER TABLE ONLY public.students DROP CONSTRAINT students_student_number_key;
ALTER TABLE ONLY public.students DROP CONSTRAINT students_pkey;
ALTER TABLE ONLY public.groups_students DROP CONSTRAINT groups_students_pkey;
ALTER TABLE ONLY public.groups DROP CONSTRAINT groups_pkey;
ALTER TABLE ONLY public.exercises DROP CONSTRAINT exercises_pkey;
ALTER TABLE ONLY public.email_messages DROP CONSTRAINT email_messages_pkey;
ALTER TABLE ONLY public.courses_users DROP CONSTRAINT courses_users_pkey;
ALTER TABLE ONLY public.courses DROP CONSTRAINT courses_pkey;
ALTER TABLE ONLY public.course_memberships DROP CONSTRAINT course_memberships_pkey;
ALTER TABLE ONLY public.chat_messages DROP CONSTRAINT chat_messages_pkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_pkey;
ALTER TABLE ONLY public.actions_exercises DROP CONSTRAINT actions_exercises_pkey;
ALTER TABLE ONLY public.action_types DROP CONSTRAINT action_types_pkey;
ALTER TABLE ONLY public.action_comments DROP CONSTRAINT action_comments_pkey;
ALTER TABLE public.users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.students ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.groups_students ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.exercises ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.email_messages ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.courses_users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.courses ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.course_memberships ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.chat_messages ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.actions_exercises ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.actions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.action_types ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.action_comments ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.users_id_seq;
DROP TABLE public.users;
DROP SEQUENCE public.students_id_seq;
DROP TABLE public.students;
DROP SEQUENCE public.groups_students_id_seq;
DROP TABLE public.groups_students;
DROP SEQUENCE public.groups_id_seq;
DROP TABLE public.groups;
DROP SEQUENCE public.exercises_id_seq;
DROP TABLE public.exercises;
DROP SEQUENCE public.email_messages_id_seq;
DROP TABLE public.email_messages;
DROP SEQUENCE public.courses_users_id_seq;
DROP TABLE public.courses_users;
DROP SEQUENCE public.courses_id_seq;
DROP TABLE public.courses;
DROP SEQUENCE public.course_memberships_id_seq;
DROP TABLE public.course_memberships;
DROP SEQUENCE public.chat_messages_id_seq;
DROP TABLE public.chat_messages;
DROP SEQUENCE public.actions_id_seq;
DROP SEQUENCE public.actions_exercises_id_seq;
DROP TABLE public.actions_exercises;
DROP TABLE public.actions;
DROP SEQUENCE public.action_types_id_seq;
DROP TABLE public.action_types;
DROP SEQUENCE public.action_comments_id_seq;
DROP TABLE public.action_comments;

