ALTER TABLE ONLY public.students DROP CONSTRAINT students_group_id_fkey;
ALTER TABLE ONLY public.notifications DROP CONSTRAINT notifications_student_id_fkey;
ALTER TABLE ONLY public.notes DROP CONSTRAINT notes_user_id_fkey;
ALTER TABLE ONLY public.notes DROP CONSTRAINT notes_student_id_fkey;
ALTER TABLE ONLY public.groups DROP CONSTRAINT groups_user_id_fkey;
ALTER TABLE ONLY public.groups DROP CONSTRAINT groups_course_id_fkey;
ALTER TABLE ONLY public.exercises DROP CONSTRAINT exercises_course_id_fkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_user_id_fkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_student_id_fkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_exercise_id_fkey;
ALTER TABLE ONLY public.users DROP CONSTRAINT users_pkey;
ALTER TABLE ONLY public.students DROP CONSTRAINT students_pkey;
ALTER TABLE ONLY public.notifications DROP CONSTRAINT notifications_pkey;
ALTER TABLE ONLY public.groups DROP CONSTRAINT groups_pkey;
ALTER TABLE ONLY public.exercises DROP CONSTRAINT exercises_pkey;
ALTER TABLE ONLY public.courses DROP CONSTRAINT courses_pkey;
ALTER TABLE ONLY public.actions DROP CONSTRAINT actions_pkey;
ALTER TABLE public.users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.students ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.notifications ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.notes ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.exercises ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.courses ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.actions ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.users_id_seq;
DROP TABLE public.users;
DROP SEQUENCE public.students_id_seq;
DROP TABLE public.students;
DROP SEQUENCE public.notifications_id_seq;
DROP TABLE public.notifications;
DROP SEQUENCE public.notes_id_seq;
DROP TABLE public.notes;
DROP SEQUENCE public.groups_id_seq;
DROP TABLE public.groups;
DROP SEQUENCE public.exercises_id_seq;
DROP TABLE public.exercises;
DROP SEQUENCE public.courses_id_seq;
DROP TABLE public.courses;
DROP SEQUENCE public.actions_id_seq;
DROP TABLE public.actions;
DROP EXTENSION plpgsql;