/* Generated by CoffeeHelper at 2013-03-13 11:30:20 */

// Generated by CoffeeScript PHP 1.3.1
(function() {

  (function($) {
    return $.fn.ajaxfilters = function(settings) {
      var defaults;
      defaults = {
        callback: null
      };
      settings = $.extend({}, defaults, settings);
      $.param.fragment.noEscape("[],");
      return this.each(function() {
        var forms, getInputParams, id, inputs, keywordInputs, pushParams, table, tbody, updateTable, visibleRows;
        table = $(this);
        id = table.attr('id');
        tbody = table.children('tbody');
        forms = $('*[data-target="' + id + '"]');
        inputs = forms.find('input, select');
        visibleRows = [];
        getInputParams = function() {
          var $i, i, params, val, _i, _len;
          params = {};
          for (_i = 0, _len = inputs.length; _i < _len; _i++) {
            i = inputs[_i];
            $i = $(i);
            val = $i.val();
            if ($i.attr('type') !== 'checkbox' || $i.is(':checked')) {
              if (val !== '') {
                params[$i.attr('name')] = val;
              }
            }
          }
          return params;
        };
        pushParams = function(mergeMode) {
          var params, state;
          state = {};
          params = getInputParams();
          state[id] = params;
          $.bbq.pushState(state, mergeMode);
        };
        inputs.change(function() {
          return pushParams(0);
        });
        pushParams(1);
        updateTable = function() {
          var key, state, val;
          state = $.bbq.getState(id);
          for (key in state) {
            val = state[key];
            forms.find('select[name=' + key + ']').val(val);
          }
          visibleRows = [];
          return tbody.children('tr').each(function() {
            var da, dataAttr, key, match, show, val, _i, _len, _ref;
            show = true;
            for (key in state) {
              val = state[key];
              dataAttr = $(this).attr('data-' + key);
              if (dataAttr != null) {
                if (dataAttr.indexOf(',') === -1) {
                  if (val !== '' && dataAttr !== val) {
                    show = false;
                  }
                } else {
                  match = false;
                  _ref = dataAttr.split(',');
                  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                    da = _ref[_i];
                    if (da === val) {
                      match = true;
                    }
                  }
                  show = match;
                }
              } else {
                show = false;
              }
            }
            $(this).toggle(show);
            if (show) {
              return visibleRows.push(this);
            }
          });
        };
        $(window).bind('hashchange', function(e) {
          return updateTable();
        });
        updateTable();
        table.tablesorter();
        keywordInputs = $('input.filter-keyword[data-target="' + id + '"]');
        keywordInputs.each(function() {
          var current, input;
          input = $(this);
          current = tbody.children('tr.highlight');
          input.keydown(function(e) {
            var check, next, vrs;
            current = tbody.children('tr.highlight');
            vrs = $(visibleRows).filter(':not(:hidden)');
            if (e.keyCode === 38) {
              if (current.length < 1) {
                next = vrs.last();
              } else {
                next = current.prev('tr:not(:hidden)');
                if (next.length < 1) {
                  next = current.prevUntil('tr:not(:hidden)').last().prev();
                }
                if (next.length < 1) {
                  next = vrs.last();
                }
              }
              next.addClass('highlight').siblings().removeClass('highlight');
              e.preventDefault();
              return false;
            } else if (e.keyCode === 40) {
              if (current.length < 1) {
                next = vrs.first();
              } else {
                next = current.next('tr:not(:hidden)');
                if (next.length < 1) {
                  next = current.nextUntil('tr:not(:hidden)').last().next();
                }
                if (next.length < 1) {
                  next = vrs.first();
                }
              }
              next.addClass('highlight').siblings().removeClass('highlight');
              e.preventDefault();
              return false;
            } else if (e.keyCode === 13) {
              if (current.length > 0) {
                window.location = current.find('a').first().attr('href');
              }
              e.preventDefault();
              return false;
            } else if (e.keyCode === 32) {
              if (current.length > 0) {
                check = current.find('input[type="checkbox"]').first();
                check.trigger('click');
              }
              e.preventDefault();
              return false;
            }
          });
          input.keyup(function(e) {
            var keyword, match, row, _i, _len, _results;
            keyword = input.val().toLowerCase();
            _results = [];
            for (_i = 0, _len = visibleRows.length; _i < _len; _i++) {
              row = visibleRows[_i];
              match = false;
              $(row).children('td').each(function() {
                if ($(this).text().toLowerCase().indexOf(keyword) >= 0) {
                  return match = true;
                }
              });
              _results.push($(row).toggle(match));
            }
            return _results;
          });
          return input.blur(function() {
            current = [];
            return tbody.children('tr').removeClass('highlight');
          });
        });
        return keywordInputs.first().focus();
      });
    };
  })(jQuery);

}).call(this);
