/* Generated by CoffeeHelper at 2013-03-03 18:08:28 */

// Generated by CoffeeScript PHP 1.3.1
(function() {

  (function($) {
    return $.fn.ajaxfilters = function(settings) {
      var defaults;
      defaults = {
        callback: null
      };
      settings = $.extend({}, defaults, settings);
      $.param.fragment.noEscape("[],");
      return this.each(function() {
        var forms, id, inputs, table, tbody;
        table = $(this);
        id = table.attr('id');
        tbody = table.children('tbody');
        forms = $('*[data-target="' + id + '"]');
        inputs = forms.find('input, select');
        inputs.change(function() {
          var i, params, state, val, _i, _len;
          params = {};
          state = {};
          for (_i = 0, _len = inputs.length; _i < _len; _i++) {
            i = inputs[_i];
            val = $(i).val();
            if (val !== '') {
              params[$(i).attr('name')] = val;
            }
          }
          state[id] = params;
          return $.bbq.pushState(state);
        });
        return $(window).bind('hashchange', function(e) {
          var key, state, val;
          state = $.bbq.getState(id);
          for (key in state) {
            val = state[key];
            forms.find('*[name=' + key + ']').val(val);
          }
          return tbody.children('tr').each(function() {
            var key, show, val;
            show = true;
            for (key in state) {
              val = state[key];
              if (val !== '' && $(this).attr('data-' + key) !== val) {
                show = false;
              }
            }
            return $(this).toggle(show);
          });
        });
      });
    };
  })(jQuery);

}).call(this);
