/* Generated by CoffeeHelper at 2012-11-15 09:26:58 */

// Generated by CoffeeScript PHP 1.3.1
(function() {

  $(document).ready(function() {
    $('.collapsable').hide();
    $('.decollapse-toggle').click(function() {
      $(this).slideUp(200).next('.collapsable').slideDown(200);
      return false;
    });
    $('.collapse-toggle').click(function() {
      $(this).parents('.collapsable').slideUp(200).prev('.decollapse-toggle').slideDown(200);
      return false;
    });
    return $('#StudentIndexFilters select').change(function() {
      return $(this).parents('form').submit();
    });
  });

}).call(this);
