<?php

class LessHelper extends AppHelper {

    public $helpers = array('Html');

    public function import($filename) {
        
        // Import and initialize less compiler
        App::import('Vendor', 'LessPHP', array('file' => 'lessphp' . DS . 'lessc.inc.php'));
        $less = new lessc;

        // Paths
        $input_file = WWW_ROOT.DS.'less'.DS.$filename.'.less';
        $output_file = WWW_ROOT.DS.'css'.DS.$filename.'.css';

        // If modified, re-compile
        if(filemtime($input_file) > filemtime($output_file)) {
            $input = file_get_contents($input_file);
            $output = "/* Generated by LessHelper at " . date("Y-m-d H:i:s") . " */\n\n";
            $output .= $less->compile($input);
            file_put_contents($output_file, $output);
        }

        // Return ready-to-use css tag
        return $this->Html->css($filename);
    }  
}

?>